version: '3.8'

services:
  django:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/app/backend/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db


  db:
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev


  node:
    build: ./frontend
    container_name: react_app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/public/:/app/frontend/public/
      - ./frontend/src/:/frontend/src
    command: npm start
    depends_on:
      - django


volumes:
  postgres_data:

