# Generated by Django 4.1.7 on 2023-04-08 14:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название экзамена до 50 символов', max_length=50, verbose_name='Название')),
                ('description', models.TextField(max_length=155, validators=[django.core.validators.MinLengthValidator(155, message='Описание должно составлять 155 символов')], verbose_name='Комментарий')),
                ('date_exam', models.DateField(verbose_name='Дата проведения')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
                'ordering': ['date_exam'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Стажер(ученик)',
                'verbose_name_plural': 'Стажеры(ученики)',
            },
        ),
        migrations.CreateModel(
            name='TestUserGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(verbose_name='Оценка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='Стажер')),
            ],
        ),
        migrations.CreateModel(
            name='TestExm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exam')),
                ('user_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testusergrade')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(verbose_name='Оценка')),
                ('comment', models.TextField(help_text='Не обязательный пункт, может быть пустым', null=True, verbose_name='Комментарий')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances_exam', to='api.exam', verbose_name='Экзамен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='api.user', verbose_name='Стажер')),
            ],
            options={
                'verbose_name': 'Успеваемость',
                'verbose_name_plural': 'Таблица успеваемости',
            },
        ),
    ]
