# Generated by Django 4.1.7 on 2023-04-09 03:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_testusergrade_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testusergrade',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'verbose_name': 'Успеваемость', 'verbose_name_plural': 'Успеваемость стажеров'},
        ),
        migrations.RemoveField(
            model_name='performance',
            name='comment',
        ),
        migrations.AlterField(
            model_name='performance',
            name='grade',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(limit_value=5, message='Максимальная оценка 5'), django.core.validators.MinValueValidator(limit_value=1, message='Минимальная оценка 1')], verbose_name='Оценка'),
        ),
        migrations.DeleteModel(
            name='TestExm',
        ),
        migrations.DeleteModel(
            name='TestUserGrade',
        ),
    ]
